#import "TradingBackendBridge.h"
#import <React/RCTLog.h>

// Import the Go framework header compiled by gomobile
// This header is automatically generated by: gomobile bind -target=ios
#import <TradingBackend/TradingBackend.h>

@implementation TradingBackendBridge

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(startBackend:(NSString *)apiKey)
{
  RCTLogInfo(@"[TradingBackendBridge] Starting Go server in background thread...");
  
  // Execute Go StartBackend blocking listener loop in background dispatch queue
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    @try {
      // Calls the Go function compiled in the framework: StartBackend(string)
      TradingBackendStartBackend(apiKey);
    } @catch (NSException *exception) {
      RCTLogError(@"[TradingBackendBridge] Fatal error running Go runtime: %@", exception.reason);
    }
  });
}

@end
